name: 'List Pull Requests'
description: 'Takes a list of Repositories and prints out currently active Pull Requests'
inputs:
  repositories:
    description: "The list of repositories."
    required: true
  token:
    description: "Token to be able to view repository pull requests"
    required: false
outputs:
  pr-list:
    description: "The List of PRs for the repositories"
    value: ${{ steps.get-pr-list.outputs.output }}

runs:
  using: 'composite'
  steps:
    - name: Login
      shell: bash
      run: |
        echo "${{ inputs.token }}" | gh auth login --with-token

    - name: Run Python Script
      shell: python
      run: |
        import requests
        import sys
        import os
        import json
        import subprocess
        from datetime import datetime

        repolist = """${{ inputs.repositories }}"""

        output = []

        for repo in repolist.splitlines():
            if (len(repo) != 0):
              # Get the PR list of the repo
              p = subprocess.Popen(f"gh pr list -R {repo} --json title,createdAt,url,isDraft,commits", stdout=subprocess.PIPE, shell=True)
              results = p.communicate()[0].decode('utf-8')
              prList = json.loads(results)

              # Generate JSON data
              jsonData = {}
              jsonData["repository"] = repo
              jsonData["pr_list"] = prList

              # Add more readable date
              for dates in jsonData["pr_list"]:
                dt = datetime.strptime(dates["createdAt"], "%Y-%m-%dT%H:%M:%SZ")
                dates["createdAtDate"] = dt.strftime('%B %d')

              output.append(jsonData)
        text_file = open("output.json", "w")
        text_file.write(json.dumps(output).replace("'", r"\'"))
        text_file.close()

    - name: Set Output
      shell: bash
      id: get-pr-list
      run: |
        OUTPUT=$(cat output.json)
        echo output=$OUTPUT >> $GITHUB_OUTPUT
